services:
  live-query:
    container_name: live-query
    build: .
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    command: gunicorn live_query_resoultion.wsgi:application -c gunicorn_config.py --bind 0.0.0.0:8002
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - chroma-db

  chroma-db:
    container_name: chroma-db
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data_gemini:/chroma

  chat-db:
      container_name: 'chat-db'
      image: postgres
      ports:
      - "5432:5432"
      environment:
        - POSTGRES_DB=chat
        - POSTGRES_USER=chat
        - POSTGRES_PASSWORD=chat
      volumes:
        - chat_data:/var/lib/postgresql/data

volumes:
  chroma_data_gemini:
  chat_data: